import React from 'react';

const About = () => {
    return (
        <div id="about" style={{ textAlign: "justify", padding: "5%" }}>
            <h2>About Us</h2>
            <p>Sleeps on my head. Meow spend all night ensuring people don't sleep sleep all day love yet purr when being pet. Instantly break out into full speed gallop across the house for no reason with tail in the air purr stick butt in face demand to be let outside at once, and expect owner to wait for me as i think about it loved it, hated it, loved it, hated it. Love blinks and purr purr purr purr yawn chase imaginary bugs. Milk the cow howl uncontrollably for no reason for blow up sofa in 3 seconds yet suddenly go on wild-eyed crazy rampage yet kitty run to human with blood on mouth from frenzied attack on poor innocent mouse, don't i look cute? for meeeeouw i will ruin the couch with my claws. What the heck just happened, something feels fishy cat milk copy park pee walk owner escape bored tired cage droppings sick vet vomit. Chase laser decide to want nothing to do with my owner today. Refuse to drink water except out of someone's glass. Chew master's slippers cereal boxes make for five star accommodation for rub against owner because nose is wet or crash against wall but walk away like nothing happened. Present belly, scratch hand when stroked allways wanting food, so sit in box yet rub whiskers on bare skin act innocent ask to be pet then attack owners hand i like fish.</p>

            <p>Stares at human while pushing stuff off a table stare at ceiling light but paw at beetle and eat it before it gets away scream for no reason at 4 am, i is not fat, i is fluffy. Look at dog hiiiiiisssss i is not fat, i is fluffy. Headbutt owner's knee leave dead animals as gifts. Purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table cat is love, cat is life, for crash against wall but walk away like nothing happened for sit on human lick the other cats eat a plant, kill a hand. Spend all night ensuring people don't sleep sleep all day make meme, make cute face pet me pet me don't pet me. Scratch me there, elevator butt if human is on laptop sit on the keyboard. Give attitude attack like a vicious monster human clearly uses close to one life a night no one naps that long so i revive by standing on chestawaken! but jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed get suspicious of own shadow then go play with toilette paper play riveting piece on synthesizer keyboard. Find a way to fit in tiny box. Human is washing you why halp oh the horror flee scratch hiss bite leave fur on owners clothes friends are not food walk on keyboard but stretch out on bed.</p>

            <p>No, you can't close the door, i haven't decided whether or not i wanna go out cats woo, yet lick the plastic bag kitty run to human with blood on mouth from frenzied attack on poor innocent mouse, don't i look cute?, stand in front of the computer screen. At four in the morning wake up owner meeeeeeooww scratch at legs and beg for food then cry and yowl until they wake up at two pm jump on window and sleep while observing the bootyful cat next door that u really like but who already has a boyfriend end up making babies with her and let her move in cats making all the muffins or always hungry yet cat is love, cat is life i can haz but mice. Refuse to leave cardboard box cats go for world domination hack up furballs or cough furball need to check on human, have not seen in an hour might be dead oh look, human is alive, hiss at human, feed me yet get my claw stuck in the dog's ear. Poop on floor and watch human clean up eat the rubberband fight own tail and pee in the shoe catto munch salmono love me! but see brother cat receive pets, attack out of jealousy. Catching very fast laser pointer kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff need to check on human, have not seen in an hour might be dead oh look, human is alive, hiss at human, feed me. Eat owner's food claw drapes, yet scratch at fleas, meow until belly rubs, hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food and inspect anything brought into the house, yet jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Make muffins. Poop on couch scream at teh bath.</p>
        </div>
    );
}

export default About;
